### ISSUE TITLE
Endorsed junior number in Percentage Metrics showing up as null

### ISSUE THREAD

**Issue by kelp-chip** [rectheworld/etrain#19]
Only caught this when I started to click endorse for people in the junior cohort.

<img width="535" alt="Screen Shot 2021-03-24 at 1 18 42 AM" src="https://user-images.githubusercontent.com/25832984/112259543-e1421f00-8c3e-11eb-84ff-70347cc68b5f.png">

**Comment by rectheworld** [comment]
Oh this guy just means they havent endorsed anyone in the junior cohort. I'm not really cleaning the nulls on the server side but i can.

**Comment by rectheworld** [comment]
closed by merge
